apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
spec:
  interval: 1h
  targetNamespace: nfs-provisioner
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
      version: ">=4.0.0"
  valuesFrom:
    - kind: Secret
      name: nfs-provisioner-secret-values
  values:
    storageClass:
      name: nfs
      defaultClass: false