apiVersion: v1
kind: Secret
metadata:
    name: nfs-provisioner-secret-values
    namespace: nfs-provisioner
stringData:
    values.yaml: ENC[AES256_GCM,data:GksWYNYZDw3xiwJHMjXBocZl9leA3Cej5CeQ78vJN0gE10lVOMQ1vGtHR41ExiXMU7ILkKX1cro=,iv:LKlczYBXDHOpLgwbqQktfVeHBCAoPLD/rWyRaGjQ97o=,tag:CPRdwmUrKRvJfK9Vbm9N2A==,type:str]
sops:
    age:
        - recipient: age1juj0yd8xjpf5slf6fdydfadvc4dn0aw930ava984z7t3qywzxstqcsalqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MmlrM09pZFJFOVJTem9s
            U2VhLzE4Q2ZCTEdoWDdkcW43Vk1FZ2JGZWlFCnZpek1tMkxDcWcwdjZDOVlvWEVq
            c3g5cU4yN3FaSmlNTkVQSnpjTmpEMEkKLS0tIExRS1k4QVEzVGZpM0xtcnNwYkQy
            ODJ1VU9NaXFnTzhkNFpad3dsMWl0a00KDRb+IlkbCfA3awfZITxQk1RfHL5UE3dZ
            8abarkkrspvGboxzoevxRF3NEUlYCNTK+ni3S+aDtzKVx9Ku04/rQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T20:38:15Z"
    mac: ENC[AES256_GCM,data:R/VQgVz88EnNZJAHYAFtmzvJCjo9voDxmqjcZ+k5Rh8Gnr6Yb4R+edJp1HF4Z4Tbem/QYLa7VNcf8GcpffQTx08FYBsrwVUpdgBOEcwKd1I9toT7j4ArW71HikSeVTSfN0ErBUrAXWsNzyRWfrfSmSf+JrvSrXeetDntLn18hDE=,iv:ef4MQlf4VHHWuotBe7YmjLc8oOCRfSaoMap/l85Mo2k=,tag:wp5YjX4PyOT0AmhAXIRmfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
