apiVersion: v1
kind: Secret
metadata:
    name: omv-secret
    namespace: flux-system
stringData:
    OMV_IP: ENC[AES256_GCM,data:SRVjK96zhJ0FhWGQ7A==,iv:gXklPZaEwstWLyUvT0vwu2wMeaQKcOfkYTdH1hvZoI4=,tag:XTDGp0KEaInDrRSW18EKGg==,type:str]
sops:
    age:
        - recipient: age1juj0yd8xjpf5slf6fdydfadvc4dn0aw930ava984z7t3qywzxstqcsalqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDN2VuVkNtZGhXTlRPTzVw
            ZFBhQWF5WHh5M3JyQ0ViTTU2ZloyVjNOMHlRCnp2T1ljdGpZcWkxNXJ5NC9FVTNG
            N1NXV3dvNWI1Smt0bU45RGgrM01pM0kKLS0tIHRZUnhjaWhEb3RKRHlFUnVEalIy
            bnE1MG9sOVM0UzBKNnhTZTZ3bWhFdlkKnK8EONWOBGXIlClJlNG6F41UZk7xA4re
            JKHQ6QNoA+1ICN/5fWkSRWOiwzMGlIS2osFdBwmKq87w2HROYLWW0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T18:57:21Z"
    mac: ENC[AES256_GCM,data:7qTDm3xDmCh9A0cDw+Yh6G+SqNDvuqFayroY0GL8H8fS8w/4s89iqK8LraX8SzyK/yWJGX53cDJi/xZhY22NSxZPHFfJD+9iH+2gltnfqCigl0ksyJ1FUhNvKzT7f+IKC7cQ9YJsgJkNjc5DyLeGNmtt3qUnJcjHrOORTqevBI0=,iv:J0mPMlua1lSCYidbaT5K3wA4hwhRIt93aK/UcrnQEu0=,tag:r3NUFO+6Ta78JfPFbOk5Eg==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
