apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:GFSH9nV/KqkDUyD1htA+h9LYmUq06yOuaKc942MMzCsthkbqOb+ejA==,iv:kGrF0GVnP+2wI+WZ2FfWlIjsLR/saInPf1YkS+EX48A=,tag:V7RxG5Dge5Bk8oQnOAiEHQ==,type:str]
sops:
    age:
        - recipient: age1juj0yd8xjpf5slf6fdydfadvc4dn0aw930ava984z7t3qywzxstqcsalqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUHdrZzVsa0JPSlRTTEQx
            eGFwVmFRcWFSclNDazRyc3FoZjZsNWZkcHk4ClRjL0pXS1R1WXVMRjFzVDNmeEp1
            RXc3RzNWSkxVLzJKQ3RnRGsrOTJSNlkKLS0tIDJlQWZxVVZ1dWdJZ0V5OXN6ZXNC
            azNPbGlpRTV2RFNtZG9vNStlVURVWWMKpmoPvba0RxAj8fQ9Erw5rvFRc9gaMIKw
            pgZiW0WXJ+nOAw3o5G9HxBKwekc7s2cxhl+Y3sxf9+LXbMFNr55pQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T12:33:16Z"
    mac: ENC[AES256_GCM,data:0k0pqBRHIkcM31W1y54U8geHFKiv86NK/PWrbalX6RYaMM/0191gQDlouhSBUe/JBwqze0Br0/c5tk2t4iPbnWGq3c1ypLXdR9Gy6ffFK4krjCEGgPZ/h9GTri65g69ExS7kezzUWBDVUBGay1wE3w3+UB0B/4rcPgmv1mv34A4=,iv:o1FKGE5xFY0ixw9YFzgMzUbIFLghZIBMfZZjADBmcKo=,tag:XzPN+ePJKYkRm7gX0mwmew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
