apiVersion: v1
kind: Secret
metadata:
    name: longhorn-secret-values
    namespace: longhorn-system
stringData:
    values.yaml: ENC[AES256_GCM,data:7KFhVkDgcKhdZAqtfD+FI5JXDq/ptKVeCAMOHrF9MJAbKVsJ51Kb961LfOl/lyE7ZBzpBHW8Ga0ENKl3tGPMQAssrFCyXaQ1uPlwb7ng,iv:3v8LDMmpsAYxDrGeKcWUdI0tnCrksqubkzAnk2Ra+UA=,tag:iuctmLQ+GXLTIADX9uSQtw==,type:str]
sops:
    age:
        - recipient: age1juj0yd8xjpf5slf6fdydfadvc4dn0aw930ava984z7t3qywzxstqcsalqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZc05HSFZaS1BMMThhTnFG
            RytHMEJTdGg4bGJ1N1dhUC9YcGJiRkVENGdNCmdITHd2NnhjOUN0QUxuckdyeDdH
            cXNyTkExeHBMbm9tYmNSNTZNN2lFR1EKLS0tIE4zYUZjS3d5TytKS2MyQWU1N3NS
            b3RWRDhGWVF4QzVkU2pKR25yR2lWTlkKx4TEaMrGaY887cqW3o1eZEcSAK4meFwJ
            A7xXw1zl7HSGusdJokrZJ4zF5UjttkArCQF8JXS9VzHqzImoLLBoIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T11:36:46Z"
    mac: ENC[AES256_GCM,data:50w27Hc6jB8+GYuP/REwAUkI+/hc1eOjM+fhUWw3KrKhv49OV0chwXIQbVm4m7BMttD+kYsV2YP3+0KXGUg3Xtk7+0RUP7b2AoYNRubPnvSdIZDOEYnHJs3bVxT3w5C8a4Zhr4ipdnlk3mqAXL5DyJJqEhGIj7uS0nax7Cz37d8=,iv:zvSL4ZR6wBZePZCuOH7nubkI/VcrX9syRqBv/+ZsfuE=,tag:yQx1IAqvUeB4HlkJzp+cbg==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
