apiVersion: v1
kind: Secret
metadata:
    name: longhorn-secret-values
    namespace: longhorn-system
stringData:
    values.yaml: ENC[AES256_GCM,data:1ljO0pRcLIV88dI4Xrz4YCQAnG3e9mqHmY4GXTqr1LZhWcottpIiOEUuIVnAbRl3WJSJ3RHI+HWkUfAUEmmxhfh34xzJWlTOC23IWMjn,iv:KEzkn3gQlxj0pXHgs6XIIFZjFY+1zeTZ0eerdiKnpWA=,tag:j3Rc3oFVqQDDKqS3iy98JA==,type:str]
sops:
    age:
        - recipient: age1juj0yd8xjpf5slf6fdydfadvc4dn0aw930ava984z7t3qywzxstqcsalqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZc05HSFZaS1BMMThhTnFG
            RytHMEJTdGg4bGJ1N1dhUC9YcGJiRkVENGdNCmdITHd2NnhjOUN0QUxuckdyeDdH
            cXNyTkExeHBMbm9tYmNSNTZNN2lFR1EKLS0tIE4zYUZjS3d5TytKS2MyQWU1N3NS
            b3RWRDhGWVF4QzVkU2pKR25yR2lWTlkKx4TEaMrGaY887cqW3o1eZEcSAK4meFwJ
            A7xXw1zl7HSGusdJokrZJ4zF5UjttkArCQF8JXS9VzHqzImoLLBoIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T10:36:56Z"
    mac: ENC[AES256_GCM,data:FdmQ96K42+xa4KmiF0nubIuzGWkHbsEtBwoJVx89OHsMscTBb4Ivv5Cl0Vco5r5ZE96Tq46gOkIglag5rD7bRvW2XmaHp5ATXC86Cm+Qv0E5toVt+W27bQ65We0kTDcVNI4gdaw+S7kFxQO0EEVwgE4+l+BHY/x6SBbczbfqclM=,iv:/phxKvikM529MPER5rKAc45qfmrUbUrXPbhleSqAKq8=,tag:BdXd8xNTfQis6CW+MCOsXQ==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
