apiVersion: v1
kind: Secret
metadata:
    name: longhorn-secret-values
    namespace: longhorn-system
stringData:
    values.yaml: ENC[AES256_GCM,data:RzgBgII/kB6WgQKSaH1pgdGy6uUdNSHCC3X782bCOzERXbL66/JsAv3zlfPb6jQCoiVO4u4fxzzFWjUaeojnUoA9K/F7T8hng15NovSUJ+JnwCFQ6A==,iv:D4cOE9WdP0U2FOlE79viQSqUJwcjmUiiR7Yx2oB8ZGg=,tag:B2LHY8c2n7tHQjitHZSzQw==,type:str]
sops:
    age:
        - recipient: age1juj0yd8xjpf5slf6fdydfadvc4dn0aw930ava984z7t3qywzxstqcsalqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZc05HSFZaS1BMMThhTnFG
            RytHMEJTdGg4bGJ1N1dhUC9YcGJiRkVENGdNCmdITHd2NnhjOUN0QUxuckdyeDdH
            cXNyTkExeHBMbm9tYmNSNTZNN2lFR1EKLS0tIE4zYUZjS3d5TytKS2MyQWU1N3NS
            b3RWRDhGWVF4QzVkU2pKR25yR2lWTlkKx4TEaMrGaY887cqW3o1eZEcSAK4meFwJ
            A7xXw1zl7HSGusdJokrZJ4zF5UjttkArCQF8JXS9VzHqzImoLLBoIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T09:32:43Z"
    mac: ENC[AES256_GCM,data:CRldvYcoPmWba5s3Cqys+9eMDjLDoBgFsnDyk1kkPZpZErgtQ+tt/KMc7dGl9zDLECu6TBx9unEKfn6HVWLe3jXEGEZlsPL8iY0MDaL2OVSNMfzjY7YAlt+QMfTMCN+a3VrwVSlQ9VUnK5HQPAYJ16XNzcDvGnDl1V1ZtpILf3M=,iv:OfmsBQDK+ahLwbnMlSqhE8p6yf5g1Bd9rvuUc0xVNq0=,tag:pSsIXIp98zQIHU2JDQVROw==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
