apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: longhorn-system
spec:
  cron: "*/10 * * * *" # Every 10 minutes for testing
  task: "backup"
  retain: 7
  concurrency: 2
  # This group is mentioned to apply the recurring job to all volumes.
  groups:
  - default