apiVersion: v1
kind: Secret
metadata:
    name: my-super-secret
    namespace: default
stringData:
    test-password: ENC[AES256_GCM,data:GgRmO7G9hUZJct7wqgKoJ3a77DrbcZuKfqI=,iv:JzzjjuyDssCmg/cfapJKaRnty2eIaBt6iUb59dJYCiE=,tag:qOcoeh4/qcm6T5wk/Ohf1Q==,type:str]
sops:
    age:
        - recipient: age1juj0yd8xjpf5slf6fdydfadvc4dn0aw930ava984z7t3qywzxstqcsalqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ1lIa2NoT3dUR0hZcFlJ
            ZE1peXFqRHJjcGx0b3IrRUlzaElVcTJkT1VRCm9qc2ZQSDgyQ25HNUZNQTIrRElD
            Z2tmb0Nxb2w3OVkrM3U5b2tETzBLSmcKLS0tIGVWYTVmZkZodURiUDdTQUpCaGdR
            ZWVvVXZLd3c5VklCcGYrL08zMEdrMlkK74QN/9+2hTixFQ2ElpgYLGRp5hBDHZGn
            zTLNAz6nwz8CO9tcSnjyDxLzmbesV463BCKgA+LUMAQ5XTmGNhNo5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T17:52:53Z"
    mac: ENC[AES256_GCM,data:qnxtbk0vuKix2VI4fXEwcKrzlJEJUUF/8EmNq0ZJjMftwS69I3vYsaXDmSX1u+0HSz1RYvROBsUvBAxMT8wePTSWnYuVIRWQR0GWH3zTVlldABlhNyRwZtr/PECyyZS7idoUGj7GnZkcOkItULx55UZfpOdWihfTI1tNCrMLscI=,iv:g8gmglLZ6PXo1e5bcSO5f+gB+b62DTjY6bq1mfg8w00=,tag:EFpXdn5B0FeUR64k/3NXmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
