apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-alexdevops-prod
  namespace: traefik
spec:
  secretName: wildcard-alexdevops-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "local.alexdevops.com"
    - "*.local.alexdevops.com"